export const PERSON_ERROR_CODES = {
  VALIDATION_FAILED: 'PERSON_VALIDATION_FAILED',
  NOT_FOUND: 'PERSON_NOT_FOUND',
  EXTERNAL_ID_CONFLICT: 'PERSON_EXTERNAL_ID_CONFLICT',
  VERSION_CONFLICT: 'PERSON_VERSION_CONFLICT',
  INVALID_STATE: 'PERSON_INVALID_STATE',
  LABOR_TYPE_NOT_FOUND: 'PERSON_LABOR_TYPE_NOT_FOUND',
  DENIED: 'PERSON_DENIED',
} as const;

export type PersonErrorCode = (typeof PERSON_ERROR_CODES)[keyof typeof PERSON_ERROR_CODES];
