export const PAYROLL_ERROR_CODES = {
  VALIDATION_FAILED: 'PAYROLL_VALIDATION_FAILED',
  DENIED: 'PAYROLL_DENIED',
  NOT_FOUND: 'PAYROLL_NOT_FOUND',
  INVALID_AMOUNT: 'PAYROLL_INVALID_AMOUNT',
  INVALID_EVENT_KIND: 'PAYROLL_INVALID_EVENT_KIND',
  PERIOD_CLOSED: 'PAYROLL_PERIOD_CLOSED',
  PERIOD_NOT_OPEN: 'PAYROLL_PERIOD_NOT_OPEN',
  PERIOD_NOT_CALCULATED: 'PAYROLL_PERIOD_NOT_CALCULATED',
  PERIOD_NOT_CLOSED: 'PAYROLL_PERIOD_NOT_CLOSED',
  FORMULA_NOT_DECIDED: 'PAYROLL_FORMULA_NOT_DECIDED',
  OPERATIONS_COUPLING_FORBIDDEN: 'PAYROLL_OPERATIONS_COUPLING_FORBIDDEN',
  DUPLICATE_EVENT: 'PAYROLL_DUPLICATE_EVENT',
} as const;
