export const ASSET_ERROR_CODES = {
  VALIDATION_FAILED: 'ASSET_VALIDATION_FAILED',
  NOT_FOUND: 'ASSET_NOT_FOUND',
  CODE_CONFLICT: 'ASSET_CODE_CONFLICT',
  PLATE_CONFLICT: 'ASSET_PLATE_CONFLICT',
  VERSION_CONFLICT: 'ASSET_VERSION_CONFLICT',
  INVALID_STATE: 'ASSET_INVALID_STATE',
  INACTIVE_RESOURCE_TYPE: 'ASSET_INACTIVE_RESOURCE_TYPE',
  INVALID_RESOURCE_TYPE: 'ASSET_INVALID_RESOURCE_TYPE',
  VEHICLE_PROFILE_REQUIRED: 'ASSET_VEHICLE_PROFILE_REQUIRED',
  VEHICLE_PROFILE_FORBIDDEN: 'ASSET_VEHICLE_PROFILE_FORBIDDEN',
  UNIT_NOT_REGISTERED: 'ASSET_UNIT_NOT_REGISTERED',
  DENIED: 'ASSET_DENIED',
} as const;

export type AssetErrorCode = (typeof ASSET_ERROR_CODES)[keyof typeof ASSET_ERROR_CODES];
