export const DASHBOARD_ERROR_CODES = {
  ACCESS_DENIED: 'DASHBOARD_ACCESS_DENIED',
  VALIDATION_FAILED: 'DASHBOARD_VALIDATION_FAILED',
} as const;

export type DashboardErrorCode = (typeof DASHBOARD_ERROR_CODES)[keyof typeof DASHBOARD_ERROR_CODES];
