export const CLIENT_ERROR_CODES = {
  VALIDATION_FAILED: 'CLIENT_VALIDATION_FAILED',
  NOT_FOUND: 'CLIENT_NOT_FOUND',
  TAX_ID_CONFLICT: 'CLIENT_TAX_ID_CONFLICT',
  VERSION_CONFLICT: 'CLIENT_VERSION_CONFLICT',
  INVALID_STATE: 'CLIENT_INVALID_STATE',
  DENIED: 'CLIENT_DENIED',
} as const;

export type ClientErrorCode = (typeof CLIENT_ERROR_CODES)[keyof typeof CLIENT_ERROR_CODES];
