export const SERVICE_ORDERS_ERROR_CODES = {
  VALIDATION_FAILED: 'SERVICE_ORDERS_VALIDATION_FAILED',
  DENIED: 'SERVICE_ORDERS_DENIED',
  NOT_FOUND: 'SERVICE_ORDERS_NOT_FOUND',
  CLIENT_NOT_FOUND: 'SERVICE_ORDERS_CLIENT_NOT_FOUND',
  SERVICE_NOT_FOUND: 'SERVICE_ORDERS_SERVICE_NOT_FOUND',
  PROPOSAL_NOT_FOUND: 'SERVICE_ORDERS_PROPOSAL_NOT_FOUND',
  PURCHASE_ORDER_NOT_FOUND: 'SERVICE_ORDERS_PURCHASE_ORDER_NOT_FOUND',
  INVALID_STATE: 'SERVICE_ORDERS_INVALID_STATE',
  INVALID_ORIGIN: 'SERVICE_ORDERS_INVALID_ORIGIN',
  UNIT_NOT_REGISTERED: 'SERVICE_ORDERS_UNIT_NOT_REGISTERED',
} as const;
