export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  REFRESH_REUSED: 'AUTH_REFRESH_REUSED',
  UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  VALIDATION_FAILED: 'AUTH_VALIDATION_FAILED',
  RATE_LIMITED: 'AUTH_RATE_LIMITED',
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
