export const CATALOG_ERROR_CODES = {
  VALIDATION_FAILED: 'CATALOG_VALIDATION_FAILED',
  NOT_FOUND: 'CATALOG_NOT_FOUND',
  CODE_CONFLICT: 'CATALOG_CODE_CONFLICT',
  VERSION_CONFLICT: 'CATALOG_VERSION_CONFLICT',
  INVALID_STATE: 'CATALOG_INVALID_STATE',
  PUBLISH_INVALID: 'CATALOG_PUBLISH_INVALID',
  INVALID_UNIT: 'CATALOG_INVALID_UNIT',
  INACTIVE_UNIT: 'CATALOG_INACTIVE_UNIT',
  INVALID_RESOURCE_TYPE: 'CATALOG_INVALID_RESOURCE_TYPE',
  INACTIVE_RESOURCE_TYPE: 'CATALOG_INACTIVE_RESOURCE_TYPE',
  INVALID_LABOR_TYPE: 'CATALOG_INVALID_LABOR_TYPE',
  INACTIVE_LABOR_TYPE: 'CATALOG_INACTIVE_LABOR_TYPE',
  DENIED: 'CATALOG_DENIED',
} as const;

export type CatalogErrorCode = (typeof CATALOG_ERROR_CODES)[keyof typeof CATALOG_ERROR_CODES];
