export const CATALOG_ERROR_CODES = {
  VALIDATION_FAILED: 'CATALOG_VALIDATION_FAILED',
  NOT_FOUND: 'CATALOG_NOT_FOUND',
  CODE_CONFLICT: 'CATALOG_CODE_CONFLICT',
  VERSION_CONFLICT: 'CATALOG_VERSION_CONFLICT',
  INVALID_STATE: 'CATALOG_INVALID_STATE',
  PUBLISH_INVALID: 'CATALOG_PUBLISH_INVALID',
  DENIED: 'CATALOG_DENIED',
} as const;

export type CatalogErrorCode = (typeof CATALOG_ERROR_CODES)[keyof typeof CATALOG_ERROR_CODES];
