/**
 * Ações técnicas tipadas — vocabulário mínimo (sem CMD empresariais pendentes).
 * Alinhado a AUTHZ-028 (infra técnica) e meta-administração de concessões.
 */
export const AUTHZ_ACTIONS = {
  ProbeExecute: 'authz:probe:execute',
  GrantCreate: 'authz:grant:create',
  GrantRevoke: 'authz:grant:revoke',
  GrantList: 'authz:grant:list',
  PlatformDiagnosticsRead: 'platform:diagnostics:read',
  ScopedRecordRead: 'authz:scoped-record:read',
  ScopedRecordList: 'authz:scoped-record:list',
  ScopedRecordUpdate: 'authz:scoped-record:update',
  ClientCreate: 'client:client:create',
  ClientRead: 'client:client:read',
  ClientList: 'client:client:list',
  ClientUpdate: 'client:client:update',
  ClientDeactivate: 'client:client:deactivate',
  ClientActivate: 'client:client:activate',
  CatalogServiceCreate: 'catalog:service:create',
  CatalogServiceRead: 'catalog:service:read',
  CatalogServiceList: 'catalog:service:list',
  CatalogServiceUpdate: 'catalog:service:update',
  CatalogServicePublish: 'catalog:service:publish',
  CatalogServiceDeactivate: 'catalog:service:deactivate',
  CatalogServiceActivate: 'catalog:service:activate',
  CatalogUnitCreate: 'catalog:unit:create',
  CatalogUnitRead: 'catalog:unit:read',
  CatalogUnitList: 'catalog:unit:list',
  CatalogUnitUpdate: 'catalog:unit:update',
  CatalogUnitDeactivate: 'catalog:unit:deactivate',
  CatalogUnitActivate: 'catalog:unit:activate',
  ResourcesResourceTypeCreate: 'resources:resource-type:create',
  ResourcesResourceTypeRead: 'resources:resource-type:read',
  ResourcesResourceTypeList: 'resources:resource-type:list',
  ResourcesResourceTypeUpdate: 'resources:resource-type:update',
  ResourcesResourceTypeDeactivate: 'resources:resource-type:deactivate',
  ResourcesResourceTypeActivate: 'resources:resource-type:activate',
  ResourcesLaborTypeCreate: 'resources:labor-type:create',
  ResourcesLaborTypeRead: 'resources:labor-type:read',
  ResourcesLaborTypeList: 'resources:labor-type:list',
  ResourcesLaborTypeUpdate: 'resources:labor-type:update',
  ResourcesLaborTypeDeactivate: 'resources:labor-type:deactivate',
  ResourcesLaborTypeActivate: 'resources:labor-type:activate',
  ResourcesAssetCreate: 'resources:asset:create',
  ResourcesAssetRead: 'resources:asset:read',
  ResourcesAssetList: 'resources:asset:list',
  ResourcesAssetUpdate: 'resources:asset:update',
  ResourcesAssetDeactivate: 'resources:asset:deactivate',
  ResourcesAssetActivate: 'resources:asset:activate',
  DocumentsDocumentCreate: 'documents:document:create',
  DocumentsDocumentRead: 'documents:document:read',
  DocumentsDocumentList: 'documents:document:list',
  DocumentsDocumentUploadVersion: 'documents:document:upload-version',
  DocumentsDocumentDownload: 'documents:document:download',
  CommercialPolicyRead: 'commercial:policy:read',
  CommercialProposalCreate: 'commercial:proposal:create',
  CommercialProposalRead: 'commercial:proposal:read',
  CommercialProposalList: 'commercial:proposal:list',
  CommercialProposalUpdate: 'commercial:proposal:update',
  CommercialProposalIssue: 'commercial:proposal:issue',
  CommercialProposalAccept: 'commercial:proposal:accept',
  CommercialProposalReject: 'commercial:proposal:reject',
  CommercialProposalExpire: 'commercial:proposal:expire',
  CommercialProposalCancel: 'commercial:proposal:cancel',
  CommercialPurchaseOrderCreate: 'commercial:purchase-order:create',
  CommercialPurchaseOrderRead: 'commercial:purchase-order:read',
  CommercialPurchaseOrderList: 'commercial:purchase-order:list',
  CommercialPurchaseOrderUpdate: 'commercial:purchase-order:update',
  CommercialPurchaseOrderRegister: 'commercial:purchase-order:register',
  CommercialPurchaseOrderCancel: 'commercial:purchase-order:cancel',
  RequestsServiceRequestCreate: 'requests:service-request:create',
  RequestsServiceRequestRead: 'requests:service-request:read',
  RequestsServiceRequestList: 'requests:service-request:list',
  RequestsServiceRequestUpdate: 'requests:service-request:update',
  RequestsServiceRequestSubmit: 'requests:service-request:submit',
  RequestsServiceRequestReview: 'requests:service-request:review',
  RequestsServiceRequestApprove: 'requests:service-request:approve',
  RequestsServiceRequestReject: 'requests:service-request:reject',
  RequestsServiceRequestCancel: 'requests:service-request:cancel',
  RequestsServiceRequestConvert: 'requests:service-request:convert',
  ServiceOrdersServiceOrderCreate: 'service-orders:service-order:create',
  ServiceOrdersServiceOrderRead: 'service-orders:service-order:read',
  ServiceOrdersServiceOrderList: 'service-orders:service-order:list',
  ServiceOrdersServiceOrderUpdate: 'service-orders:service-order:update',
  ServiceOrdersServiceOrderPrepare: 'service-orders:service-order:prepare',
  ServiceOrdersServiceOrderRelease: 'service-orders:service-order:release',
  ServiceOrdersServiceOrderCancel: 'service-orders:service-order:cancel',
} as const;

export type AuthzAction = (typeof AUTHZ_ACTIONS)[keyof typeof AUTHZ_ACTIONS];

const ACTION_SET = new Set<string>(Object.values(AUTHZ_ACTIONS));

export function isAuthzAction(value: string): value is AuthzAction {
  return ACTION_SET.has(value);
}
