export const RECURRING_BILLING_ERROR_CODES = {
  INVALID_COMPETENCE: 'RECURRING_INVALID_COMPETENCE',
  SCHEDULE_NOT_ACTIVE: 'RECURRING_SCHEDULE_NOT_ACTIVE',
  SUBJECT_NOT_ELIGIBLE: 'RECURRING_SUBJECT_NOT_ELIGIBLE',
  COMPETENCE_BEFORE_START: 'RECURRING_COMPETENCE_BEFORE_START',
  COMPETENCE_AFTER_END: 'RECURRING_COMPETENCE_AFTER_END',
  COMPETENCE_CANCELLED: 'RECURRING_COMPETENCE_CANCELLED',
  DUPLICATE_PERIOD_BILLING: 'RECURRING_DUPLICATE_PERIOD_BILLING',
  INVALID_PRORATION: 'RECURRING_INVALID_PRORATION',
  INVALID_CANCELLATION: 'RECURRING_INVALID_CANCELLATION',
} as const;

export type RecurringBillingErrorCode =
  (typeof RECURRING_BILLING_ERROR_CODES)[keyof typeof RECURRING_BILLING_ERROR_CODES];

export class RecurringBillingError extends Error {
  constructor(
    readonly code: RecurringBillingErrorCode,
    readonly detail?: string,
  ) {
    super(code);
    this.name = 'RecurringBillingError';
  }
}
