export const TRANSPORT_DISPATCH_ERROR_CODES = {
  INVALID_DISPATCH_STEP: 'TRANSPORT_INVALID_DISPATCH_STEP',
  VEHICLE_CONFLICT: 'TRANSPORT_VEHICLE_CONFLICT',
  DRIVER_CONFLICT: 'TRANSPORT_DRIVER_CONFLICT',
  ASSIGNMENT_MISSING: 'TRANSPORT_ASSIGNMENT_MISSING',
  ROUTE_REQUIRED: 'TRANSPORT_ROUTE_REQUIRED',
  ARRIVAL_EVIDENCE_REQUIRED: 'TRANSPORT_ARRIVAL_EVIDENCE_REQUIRED',
  ARRIVAL_BEFORE_DEPARTURE: 'TRANSPORT_ARRIVAL_BEFORE_DEPARTURE',
  EXECUTION_IMMUTABLE: 'TRANSPORT_EXECUTION_IMMUTABLE',
  TRIP_TERMINAL: 'TRANSPORT_TRIP_TERMINAL',
} as const;

export type TransportDispatchErrorCode =
  (typeof TRANSPORT_DISPATCH_ERROR_CODES)[keyof typeof TRANSPORT_DISPATCH_ERROR_CODES];

export class TransportDispatchError extends Error {
  constructor(
    readonly code: TransportDispatchErrorCode,
    readonly conflictingTripIds: string[] = [],
  ) {
    super(code);
    this.name = 'TransportDispatchError';
  }
}
