export const REPORT_ERROR_CODES = {
  ACCESS_DENIED: 'REPORT_ACCESS_DENIED',
  INVALID_REQUEST: 'REPORT_INVALID_REQUEST',
  NOT_FOUND: 'REPORT_NOT_FOUND',
  NOT_READY: 'REPORT_NOT_READY',
  FORMAT_UNSUPPORTED: 'REPORT_FORMAT_UNSUPPORTED',
  CANCELLED: 'REPORT_CANCELLED',
} as const;

export type ReportErrorCode = (typeof REPORT_ERROR_CODES)[keyof typeof REPORT_ERROR_CODES];
