export const AUTHZ_ERROR_CODES = {
  UNAUTHENTICATED: 'AUTHZ_UNAUTHENTICATED',
  DENIED: 'AUTHZ_DENIED',
  VALIDATION_FAILED: 'AUTHZ_VALIDATION_FAILED',
} as const;

export type AuthzErrorCode = (typeof AUTHZ_ERROR_CODES)[keyof typeof AUTHZ_ERROR_CODES];

export const AUTHZ_DENY_REASONS = {
  NO_IDENTITY: 'NO_IDENTITY',
  NO_ACTIVE_GRANT: 'NO_ACTIVE_GRANT',
  SCOPE_MISMATCH: 'SCOPE_MISMATCH',
  SCOPE_NOT_FOUND: 'SCOPE_NOT_FOUND',
  SELF_ESCALATION: 'SELF_ESCALATION',
  GRANT_EXPIRED: 'GRANT_EXPIRED',
  GRANT_REVOKED: 'GRANT_REVOKED',
  FAIL_CLOSED: 'FAIL_CLOSED',
  INVALID_RESOURCE_ID: 'INVALID_RESOURCE_ID',
} as const;

export type AuthzDenyReason = (typeof AUTHZ_DENY_REASONS)[keyof typeof AUTHZ_DENY_REASONS];
