export const DOCUMENT_ERROR_CODES = {
  NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  VERSION_NOT_FOUND: 'DOCUMENT_VERSION_NOT_FOUND',
  DENIED: 'DOCUMENT_ACCESS_DENIED',
  INVALID_CATEGORY: 'DOCUMENT_INVALID_CATEGORY',
  INVALID_MIME: 'DOCUMENT_INVALID_MIME',
  INVALID_EXTENSION: 'DOCUMENT_INVALID_EXTENSION',
  MAGIC_BYTES_MISMATCH: 'DOCUMENT_MAGIC_BYTES_MISMATCH',
  FILE_TOO_LARGE: 'DOCUMENT_FILE_TOO_LARGE',
  TOO_MANY_FILES: 'DOCUMENT_TOO_MANY_FILES',
  UNIT_NOT_REGISTERED: 'DOCUMENT_UNIT_NOT_REGISTERED',
  MAX_VERSIONS_REACHED: 'DOCUMENT_MAX_VERSIONS_REACHED',
  STORAGE_FAILURE: 'DOCUMENT_STORAGE_FAILURE',
  DOWNLOAD_TOKEN_INVALID: 'DOCUMENT_DOWNLOAD_TOKEN_INVALID',
  DOWNLOAD_TOKEN_EXPIRED: 'DOCUMENT_DOWNLOAD_TOKEN_EXPIRED',
  INVALID_INPUT: 'DOCUMENT_INVALID_INPUT',
} as const;

export type DocumentErrorCode = (typeof DOCUMENT_ERROR_CODES)[keyof typeof DOCUMENT_ERROR_CODES];
