export const SUPPLIER_ERROR_CODES = {
  VALIDATION_FAILED: 'SUPPLIER_VALIDATION_FAILED',
  NOT_FOUND: 'SUPPLIER_NOT_FOUND',
  TAX_ID_CONFLICT: 'SUPPLIER_TAX_ID_CONFLICT',
  TAX_ID_INVALID: 'SUPPLIER_TAX_ID_INVALID',
  VERSION_CONFLICT: 'SUPPLIER_VERSION_CONFLICT',
  INVALID_STATE: 'SUPPLIER_INVALID_STATE',
  INACTIVE: 'SUPPLIER_INACTIVE',
  DENIED: 'SUPPLIER_DENIED',
} as const;

export type SupplierErrorCode = (typeof SUPPLIER_ERROR_CODES)[keyof typeof SUPPLIER_ERROR_CODES];
