export const REQUESTS_ERROR_CODES = {
  VALIDATION_FAILED: 'REQUESTS_VALIDATION_FAILED',
  DENIED: 'REQUESTS_DENIED',
  NOT_FOUND: 'REQUESTS_SERVICE_REQUEST_NOT_FOUND',
  INVALID_STATE: 'REQUESTS_SERVICE_REQUEST_INVALID_STATE',
  VERSION_CONFLICT: 'REQUESTS_SERVICE_REQUEST_VERSION_CONFLICT',
  CLIENT_NOT_FOUND: 'REQUESTS_CLIENT_NOT_FOUND',
  CLIENT_INACTIVE: 'REQUESTS_CLIENT_INACTIVE',
  UNIT_NOT_REGISTERED: 'REQUESTS_UNIT_NOT_REGISTERED',
  SERVICE_NOT_FOUND: 'REQUESTS_SERVICE_NOT_FOUND',
  DOCUMENT_NOT_FOUND: 'REQUESTS_DOCUMENT_NOT_FOUND',
  PROPOSAL_NOT_FOUND: 'REQUESTS_PROPOSAL_NOT_FOUND',
  PURCHASE_ORDER_NOT_FOUND: 'REQUESTS_PURCHASE_ORDER_NOT_FOUND',
  PURCHASE_ORDER_INVALID_STATE: 'REQUESTS_PURCHASE_ORDER_INVALID_STATE',
  PURCHASE_ORDER_CLIENT_MISMATCH: 'REQUESTS_PURCHASE_ORDER_CLIENT_MISMATCH',
  CONVERSION_NOT_READY: 'REQUESTS_CONVERSION_NOT_READY',
  CONVERSION_NOT_ALLOWED: 'REQUESTS_CONVERSION_NOT_ALLOWED',
  DUPLICATE_IDEMPOTENCY: 'REQUESTS_DUPLICATE_IDEMPOTENCY',
} as const;

export type RequestsErrorCode = (typeof REQUESTS_ERROR_CODES)[keyof typeof REQUESTS_ERROR_CODES];
