export const PROCUREMENT_ERROR_CODES = {
  VALIDATION_FAILED: 'PROCUREMENT_VALIDATION_FAILED',
  NOT_FOUND: 'PROCUREMENT_NOT_FOUND',
  DENIED: 'PROCUREMENT_DENIED',
  INVALID_STATE: 'PROCUREMENT_INVALID_STATE',
  VERSION_CONFLICT: 'PROCUREMENT_VERSION_CONFLICT',
  NOT_APPROVED: 'PROCUREMENT_NOT_APPROVED',
  HAS_ORDER: 'PROCUREMENT_HAS_ORDER',
  HAS_RECEIPTS: 'PROCUREMENT_HAS_RECEIPTS',
  OVER_RECEIPT: 'PROCUREMENT_OVER_RECEIPT',
  DUPLICATE_ORDER: 'PROCUREMENT_DUPLICATE_ORDER',
  LINE_REQUIRED: 'PROCUREMENT_LINE_REQUIRED',
  INVOICE_DUPLICATE: 'SUPPLIER_INVOICE_DUPLICATE',
  INVOICE_AMOUNT_MISMATCH: 'SUPPLIER_INVOICE_AMOUNT_MISMATCH',
  MATCH_NOT_FOUND: 'THREE_WAY_MATCH_NOT_FOUND',
} as const;

export type ProcurementErrorCode = (typeof PROCUREMENT_ERROR_CODES)[keyof typeof PROCUREMENT_ERROR_CODES];
