export const COMMERCIAL_ERROR_CODES = {
  VALIDATION_FAILED: 'COMMERCIAL_VALIDATION_FAILED',
  DENIED: 'COMMERCIAL_DENIED',
  NOT_FOUND: 'COMMERCIAL_PROPOSAL_NOT_FOUND',
  VERSION_NOT_FOUND: 'COMMERCIAL_PROPOSAL_VERSION_NOT_FOUND',
  INVALID_STATE: 'COMMERCIAL_PROPOSAL_INVALID_STATE',
  VERSION_CONFLICT: 'COMMERCIAL_PROPOSAL_VERSION_CONFLICT',
  CLIENT_NOT_FOUND: 'COMMERCIAL_CLIENT_NOT_FOUND',
  CLIENT_INACTIVE: 'COMMERCIAL_CLIENT_INACTIVE',
  UNIT_NOT_REGISTERED: 'COMMERCIAL_UNIT_NOT_REGISTERED',
  SERVICE_NOT_FOUND: 'COMMERCIAL_SERVICE_NOT_FOUND',
  DOCUMENT_NOT_FOUND: 'COMMERCIAL_DOCUMENT_NOT_FOUND',
  ACCEPTANCE_EVIDENCE_REQUIRED: 'COMMERCIAL_ACCEPTANCE_EVIDENCE_REQUIRED',
  REVISION_NOT_ALLOWED: 'COMMERCIAL_REVISION_NOT_ALLOWED',
  DRAFT_EXISTS: 'COMMERCIAL_DRAFT_VERSION_EXISTS',
} as const;

export type CommercialErrorCode = (typeof COMMERCIAL_ERROR_CODES)[keyof typeof COMMERCIAL_ERROR_CODES];
